In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
dataset['classification_yes'].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [8]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [9]:
dependent=dataset[['classification_yes']]

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
grid_param={'n_estimators':[100,500,1000,1500],'criterion':['gini', 'entropy', 'log_loss'],'max_features':['sqrt', 'log2', None]
            ,'bootstrap':[True, False]
            ,'warm_start':[True, False]}

RF_grid=GridSearchCV(RandomForestClassifier(), grid_param,refit=True, verbose=3,n_jobs=-1, scoring='f1_weighted')

RF_grid.fit(x_train,y_train)

RF_pred=RF_grid.predict(x_test)

Fitting 5 folds for each of 144 candidates, totalling 720 fits

C:\Users\DEEPAK\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [13]:
print("The best Hyperfactor Parameter are\n",RF_grid.best_params_)
re=RF_grid.cv_results_

from sklearn.metrics import confusion_matrix
cm_RF=confusion_matrix(y_test,RF_pred)

from sklearn.metrics import classification_report
class_report_RF=classification_report(y_test,RF_pred)
print("\nRandomForestClassifier:\n",class_report_RF)

The best Hyperfactor Parameter are
 {'bootstrap': False, 'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100, 'warm_start': True}

RandomForestClassifier:
               precision    recall  f1-score   support

           0       0.98      0.98      0.98        45
           1       0.99      0.99      0.99        75

    accuracy                           0.98       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.98      0.98       120

In [14]:
import pickle
filename="final_model_classification.sav"

pickle.dump(RF_grid, open(filename, 'wb'))

i1=int(input("Enter the age: "))
i2=int(input("Enter the bp: "))
i3b=int(input("Enter the sg-b(yes-1 or no-0): "))
i3c=int(input("Enter the sg-c(yes-1 or no-0): "))
i3d=int(input("Enter the sg-d(yes-1 or no-0): "))
i3e=int(input("Enter the sg-e(yes-1 or no-0): "))
i4=int(input("Enter the al: "))
i5=int(input("Enter the su: "))
i6=int(input("Enter the rbc(normal-1 or abnormal-0): "))
i7=int(input("Enter the pc(normal-1 or abnormal-0): "))
i8=int(input("Enter the pcc(present-1 or notPresent-0): "))
i9=int(input("Enter the ba(present-1 or notPresent-0: "))
i10=int(input("Enter the bgr: "))
i11=int(input("Enter the bu: "))
i12=int(input("Enter the sc: "))
i13=int(input("Enter the sod: "))
i14=int(input("Enter the pot: "))
i15=int(input("Enter the hrmo: "))
i16=int(input("Enter the pvc: "))
i17=int(input("Enter the wc: "))
i18=int(input("Enter the rc: "))
i19=int(input("Enter the htn(yes-1 or no-0): "))
i20=int(input("Enter the dm (yes-1 or no-0): "))
i21=int(input("Enter the cad (yes-1 or no-0): "))
i22=int(input("Enter the appet (yes-1 or poor-0): "))
i23=int(input("Enter the pe (yes-1 or poor-0): "))
i24=int(input("Enter the ane (yes-1 or no-0): "))

preinput=sc.transform([[i1,i2,i3b,i3c,i3d,i3e,i4,i5,i6,i7,i8,i9,i10,i11,i12,i13,i14,i15,i16,i17,i18,i19,i20,i21,i22,i23,i24]])

preinput

Enter the age: 35
Enter the bp: 125
Enter the sg-b(yes-1 or no-0): 1
Enter the sg-c(yes-1 or no-0): 0
Enter the sg-d(yes-1 or no-0): 0
Enter the sg-e(yes-1 or no-0): 0
Enter the al: 0
Enter the su: 123
Enter the rbc(normal-1 or abnormal-0): 1
Enter the pc(normal-1 or abnormal-0): 1
Enter the pcc(present-1 or notPresent-0): 0
Enter the ba(present-1 or notPresent-0: 0
Enter the bgr: 456
Enter the bu: 789
Enter the sc: 987
Enter the sod: 654
Enter the pot: 321
Enter the hrmo: 159
Enter the pvc: 357
Enter the wc: 153
Enter the rc: 759
Enter the htn(yes-1 or no-0): 1
Enter the dm (yes-1 or no-0): 1
Enter the cad (yes-1 or no-0): 1
Enter the appet (yes-1 or poor-0): 0
Enter the pe (yes-1 or poor-0): 0
Enter the ane (yes-1 or no-0): 0

C:\Users\DEEPAK\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([[-1.05014360e+00,  3.72887888e+00,  1.36476908e-01,
        -3.65781760e-01, -1.98494771e+00, -1.15246517e+00,
        -5.47797855e-01, -1.40747292e+00, -1.64377552e+00,
        -4.22085969e+00, -4.75951599e+00, -3.51700868e+00,
         5.54362564e+02,  2.02564811e+03,  2.38743731e+03,
         1.73237170e+03,  2.41949487e+03,  4.66248143e+02,
         8.89308713e+02,  5.08855876e+02,  3.47640456e+03,
         1.35902126e+00,  1.36977686e+00,  3.33623062e+00,
        -1.97350876e+00, -5.12292337e-01, -4.38529010e-01]])

In [15]:
load_model=pickle.load(open("final_model_classification.sav",'rb'))

result=load_model.predict(preinput)

result

array([1])